version: 2

sources:
  - name: staging
    database: coherent-surf-415008
    schema: final_dataset

    tables:
      - name: organograms23
      - name: organograms22
      - name: organograms21
      - name: organograms20
      